// Generated by scripts/generate-config-schema.py. Do not edit.
export const CONFIG_SCHEMA_VERSION = 4 as const;
export const CONFIG_MIME_TYPE = "application/vnd.sms-forwarding.config" as const;
export const BACKUP_ENVELOPE = {
  magic: "SMSCFG01",
  version: 1,
  kdfId: 1,
  iterations: 210000,
  saltBytes: 16,
  cipherId: 1,
  ivBytes: 12,
  tagBytes: 16,
  headerBytes: 44,
  byteOrder: "little-endian",
  aad: "header",
  aadBytes: 44,
  maxEncryptedBytes: 32828
} as const;
export const CONFIG_FIELD_LIMITS = {
  "deviceName": 64,
  "hostname": 32,
  "notificationLocale": 16,
  "smtpServer": 253,
  "smtpUser": 254,
  "smtpPass": 256,
  "smtpSendTo": 254,
  "adminPhone": 32,
  "numberBlackList": 1024,
  "webUsername": 64,
  "webPassword": 96,
  "wifiSsid": 31,
  "wifiPassword": 63,
  "pushName": 64,
  "pushUrl": 512,
  "pushKey1": 256,
  "pushKey2": 256,
  "pushTitleTemplate": 256,
  "pushBodyTemplate": 2048,
  "pushCustomBody": 2048
} as const;
export const CONFIG_VALUE_LIMITS = {
  networkMode: { min: 0, max: 2, default: 0 },
  heartbeatInterval: { min: 1, max: 240, default: 6 }
} as const;
export const NOTIFICATION_LOCALES = ["zh-TW", "zh-CN", "en"] as const;
