// Generated by scripts/generate-config-schema.py. Do not edit.
#ifndef CONFIG_SCHEMA_GENERATED_H
#define CONFIG_SCHEMA_GENERATED_H

#include <stddef.h>
#include <stdint.h>

constexpr const char CONFIG_FORMAT[] = "sms-forwarding-config";
constexpr const char CONFIG_MIME_TYPE[] = "application/vnd.sms-forwarding.config";
constexpr uint16_t CONFIG_SCHEMA_VERSION = 3;
constexpr size_t MAX_CONFIG_BLOB_SIZE = 32768;
constexpr const char BACKUP_ENVELOPE_MAGIC[] = "SMSCFG01";
constexpr uint16_t BACKUP_ENVELOPE_VERSION = 1;
constexpr uint8_t BACKUP_KDF_ID = 1;
constexpr uint32_t BACKUP_KDF_ITERATIONS = 210000;
constexpr size_t BACKUP_SALT_BYTES = 16;
constexpr uint8_t BACKUP_CIPHER_ID = 1;
constexpr size_t BACKUP_IV_BYTES = 12;
constexpr size_t BACKUP_TAG_BYTES = 16;
constexpr size_t BACKUP_HEADER_BYTES = 44;
constexpr bool BACKUP_LITTLE_ENDIAN = true;
constexpr size_t BACKUP_AAD_BYTES = 44;
constexpr size_t MAX_ENCRYPTED_CONFIG_BYTES = 32828;
#define MAX_PUSH_CHANNELS 5
#define MAX_WEB_ACCOUNTS 10

enum PushType {
  PUSH_TYPE_NONE = 0,
  PUSH_TYPE_POST_JSON = 1,
  PUSH_TYPE_BARK = 2,
  PUSH_TYPE_GET = 3,
  PUSH_TYPE_DINGTALK = 4,
  PUSH_TYPE_PUSHPLUS = 5,
  PUSH_TYPE_SERVERCHAN = 6,
  PUSH_TYPE_CUSTOM = 7,
  PUSH_TYPE_FEISHU = 8,
  PUSH_TYPE_GOTIFY = 9,
  PUSH_TYPE_TELEGRAM = 10,
  PUSH_TYPE_DISCORD = 11,
  PUSH_TYPE_NTFY = 12,
};

constexpr size_t MAX_DEVICE_NAME_BYTES = 64;
constexpr size_t MAX_HOSTNAME_LENGTH = 32;
constexpr const char PORTABLE_DEVICE_NAME[] = "Portable backup";
constexpr const char PORTABLE_HOSTNAME[] = "portable-backup";
constexpr size_t MAX_NOTIFICATION_LOCALE_BYTES = 16;
constexpr size_t MAX_SMTP_SERVER_BYTES = 253;
constexpr size_t MAX_SMTP_USER_BYTES = 254;
constexpr size_t MAX_SMTP_PASSWORD_BYTES = 256;
constexpr size_t MAX_SMTP_RECIPIENT_BYTES = 254;
constexpr size_t MAX_ADMIN_PHONE_BYTES = 32;
constexpr size_t MAX_BLACKLIST_BYTES = 1024;
constexpr size_t MAX_WEB_USERNAME_BYTES = 64;
constexpr size_t MAX_WEB_PASSWORD_BYTES = 96;
constexpr size_t MAX_PUSH_NAME_BYTES = 64;
constexpr size_t MAX_PUSH_URL_BYTES = 512;
constexpr size_t MAX_PUSH_KEY1_BYTES = 256;
constexpr size_t MAX_PUSH_KEY2_BYTES = 256;
constexpr size_t MAX_TITLE_TEMPLATE_BYTES = 256;
constexpr size_t MAX_BODY_TEMPLATE_BYTES = 2048;
constexpr size_t MAX_CUSTOM_BODY_BYTES = 2048;
constexpr size_t MAX_RENDERED_TITLE_BYTES = 256;
constexpr size_t MAX_RENDERED_BODY_BYTES = 8192;
constexpr size_t MAX_RENDERED_CUSTOM_BODY_BYTES = 8192;
constexpr const char NOTIFICATION_LOCALE_ZH_TW[] = "zh-TW";
constexpr const char NOTIFICATION_LOCALE_ZH_CN[] = "zh-CN";
constexpr const char NOTIFICATION_LOCALE_EN[] = "en";
constexpr const char DEFAULT_NOTIFICATION_LOCALE[] = "zh-TW";

#endif
