#ifndef FIRMWARE_VERSION_GENERATED_H
#define FIRMWARE_VERSION_GENERATED_H

#define FIRMWARE_RELEASE_VERSION "0.1.0"
#define FIRMWARE_DEV_BUILD 3
#define FIRMWARE_DEV_BUILD_TEXT "3"
#define FIRMWARE_RELEASE_LABEL "0.1.0 (3)"

#ifndef FIRMWARE_IS_RELEASE
#define FIRMWARE_IS_RELEASE 0
#endif

#endif
