import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { gzipSync } from "node:zlib";

const MAX_GZIP_BYTES = 256 * 1024;
const PANELS = ["overview", "sim", "inbox", "settings", "push", "keepalive", "diagnose", "atterm", "log"];
const outputHeader = new URL("../../code/web_assets.h", import.meta.url);
const outputSource = new URL("../../code/web_assets.cpp", import.meta.url);

function gzip(bytes) {
	return gzipSync(bytes, { level: 9 });
}

function hash(bytes, length) {
	return createHash("sha256").update(bytes).digest("hex").slice(0, length);
}

function rows(bytes) {
	const output = [];
	for (let offset = 0; offset < bytes.length; offset += 16) {
		output.push(`  ${[...bytes.subarray(offset, offset + 16)].map((byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")},`);
	}
	return output.join("\n");
}

function asset(name, bytes, mime) {
	return `static const uint8_t ${name}_DATA[] = {\n${rows(bytes)}\n};\nconst WebAsset ${name} = { ${name}_DATA, sizeof(${name}_DATA), "${mime}", "\\\"${hash(bytes, 16)}\\\"" };\n`;
}

const html = await readFile(new URL("../build/index.html", import.meta.url));
const provisioning = await readFile(new URL("../build/provisioning.html", import.meta.url));
if (/<script\s+[^>]*src=|<link\s+[^>]*rel=["']stylesheet["'][^>]*href=/.test(html.toString())) {
	throw new Error("The production page is not fully inline");
}

const bundle = gzip(html);
const provisioningBundle = gzip(provisioning);
const emptyBundle = gzip(Buffer.alloc(0));
if (bundle.length > MAX_GZIP_BYTES) throw new Error(`Bundle is too large: ${bundle.length} bytes`);

const header = `#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <stddef.h>
#include <stdint.h>

struct WebAsset {
  const uint8_t* data;
  size_t length;
  const char* mime;
  const char* etag;
};

extern const char WEB_ASSET_HASH[];
extern const WebAsset WEB_INDEX;
extern const WebAsset WEB_APP_CSS;
extern const WebAsset WEB_APP_JS;
extern const WebAsset WEB_AP;

const WebAsset* findWebPanelAsset(const char* name);

#endif
`;

const panelChecks = PANELS.map((name) => `  if (strcmp(name, "${name}") == 0) return &WEB_INDEX;`).join("\n");
const source = `#include "web_assets.h"
#include <string.h>

// Generated by web/scripts/package.mjs; edit the sources under web/ instead.
const char WEB_ASSET_HASH[] = "${hash(bundle, 12)}";

${asset("WEB_INDEX", bundle, "text/html; charset=utf-8")}
${asset("WEB_APP_CSS", emptyBundle, "text/css; charset=utf-8")}
${asset("WEB_APP_JS", emptyBundle, "application/javascript")}
${asset("WEB_AP", provisioningBundle, "text/html; charset=utf-8")}
const WebAsset* findWebPanelAsset(const char* name) {
  if (!name) return nullptr;
${panelChecks}
  return nullptr;
}
`;

if (process.argv.includes("--check")) {
	const current = await Promise.all([
		readFile(outputHeader, "utf8").catch(() => ""),
		readFile(outputSource, "utf8").catch(() => "")
	]);
	if (current[0] !== header || current[1] !== source) {
		throw new Error("Web assets are out of date; run: npm --prefix web run build");
	}
} else {
	await Promise.all([writeFile(outputHeader, header), writeFile(outputSource, source)]);
	console.log(`Web bundle: ${html.length} bytes raw, ${bundle.length} bytes gzip`);
}
