// Generated by tools/generate-config-schema.py. Do not edit.
#ifndef CONFIG_SCHEMA_GENERATED_H
#define CONFIG_SCHEMA_GENERATED_H

#include <stddef.h>
#include <stdint.h>

constexpr const char CONFIG_FORMAT[] = "sms-forwarding-config";
constexpr const char CONFIG_MIME_TYPE[] = "application/vnd.sms-forwarding.config";
constexpr uint16_t CONFIG_SCHEMA_VERSION = 6;
constexpr size_t MAX_CONFIG_BLOB_SIZE = 32768;
constexpr size_t CONFIG_WIRE_HEADER_BYTES = 20;
constexpr size_t CONFIG_WIRE_STRING_LENGTH_PREFIX_BYTES = 2;
constexpr size_t CONFIG_WIRE_ARRAY_COUNT_BYTES = 1;
constexpr size_t CONFIG_WIRE_PAYLOAD_BYTES = 26736;
constexpr size_t CONFIG_WORST_CASE_BINARY_BYTES = 26756;
constexpr size_t CONFIG_BINARY_HEADROOM_BYTES = 6012;
constexpr const char BACKUP_ENVELOPE_MAGIC[] = "SMSCFG01";
constexpr uint16_t BACKUP_ENVELOPE_VERSION = 1;
constexpr uint8_t BACKUP_KDF_ID = 1;
constexpr uint32_t BACKUP_KDF_ITERATIONS = 210000;
constexpr size_t BACKUP_SALT_BYTES = 16;
constexpr uint8_t BACKUP_CIPHER_ID = 1;
constexpr size_t BACKUP_IV_BYTES = 12;
constexpr size_t BACKUP_TAG_BYTES = 16;
constexpr size_t BACKUP_HEADER_BYTES = 44;
constexpr bool BACKUP_LITTLE_ENDIAN = true;
constexpr size_t BACKUP_AAD_BYTES = 44;
constexpr size_t MAX_ENCRYPTED_CONFIG_BYTES = 32828;
#define MAX_PUSH_CHANNELS 5
#define MAX_WEB_ACCOUNTS 10
#define MAX_WIFI_PROFILES 5
#define MAX_SIM_CREDENTIALS 5
#define MAX_SCHED_TASKS 6

enum PushType {
  PUSH_TYPE_NONE = 0,
  PUSH_TYPE_POST_JSON = 1,
  PUSH_TYPE_BARK = 2,
  PUSH_TYPE_GET = 3,
  PUSH_TYPE_DINGTALK = 4,
  PUSH_TYPE_PUSHPLUS = 5,
  PUSH_TYPE_SERVERCHAN = 6,
  PUSH_TYPE_CUSTOM = 7,
  PUSH_TYPE_FEISHU = 8,
  PUSH_TYPE_GOTIFY = 9,
  PUSH_TYPE_TELEGRAM = 10,
  PUSH_TYPE_DISCORD = 11,
  PUSH_TYPE_NTFY = 12,
};

enum NetworkMode {
  NETWORK_MODE_WIFI_ONLY = 0,
  NETWORK_MODE_4G_ONLY = 1,
  NETWORK_MODE_MIX = 2,
};

enum WifiTxPowerQuarterDbm {
  WIFI_TX_POWER_2DBM = 8,
  WIFI_TX_POWER_5DBM = 20,
  WIFI_TX_POWER_7DBM = 28,
  WIFI_TX_POWER_8_5DBM = 34,
  WIFI_TX_POWER_11DBM = 44,
  WIFI_TX_POWER_13DBM = 52,
  WIFI_TX_POWER_14DBM = 56,
  WIFI_TX_POWER_15DBM = 60,
  WIFI_TX_POWER_16_5DBM = 66,
  WIFI_TX_POWER_18DBM = 72,
  WIFI_TX_POWER_20DBM = 80,
};

constexpr size_t MAX_DEVICE_NAME_BYTES = 64;
constexpr size_t MAX_HOSTNAME_LENGTH = 32;
constexpr const char PORTABLE_DEVICE_NAME[] = "Portable backup";
constexpr const char PORTABLE_HOSTNAME[] = "portable-backup";
constexpr size_t MAX_NOTIFICATION_LOCALE_BYTES = 16;
constexpr size_t MAX_SMTP_SERVER_BYTES = 253;
constexpr size_t MAX_SMTP_USER_BYTES = 254;
constexpr size_t MAX_SMTP_PASSWORD_BYTES = 256;
constexpr size_t MAX_SMTP_RECIPIENT_BYTES = 256;
constexpr size_t MAX_ADMIN_PHONE_BYTES = 64;
constexpr size_t MAX_BLACKLIST_BYTES = 1024;
constexpr size_t MAX_FORWARD_RULES_BYTES = 2048;
constexpr size_t MAX_WEB_USERNAME_BYTES = 64;
constexpr size_t MAX_WEB_PASSWORD_BYTES = 96;
constexpr size_t MAX_WIFI_SSID_BYTES = 31;
constexpr size_t MAX_WIFI_PASSWORD_BYTES = 63;
constexpr size_t MAX_KEEPALIVE_TARGET_BYTES = 64;
constexpr size_t MAX_KEEPALIVE_URL_BYTES = 256;
constexpr size_t MAX_KEEPALIVE_PROFILE_BYTES = 64;
constexpr size_t MAX_NTP_SERVER_BYTES = 128;
constexpr size_t MAX_APN_BYTES = 96;
constexpr size_t MAX_OPERATOR_PLMN_BYTES = 16;
constexpr size_t MAX_PHONE_NUMBER_BYTES = 32;
constexpr size_t MAX_SIM_ICCID_BYTES = 22;
constexpr size_t MAX_SIM_PIN_BYTES = 8;
constexpr size_t MAX_SIM_PUK_BYTES = 8;
constexpr size_t MAX_SCHEDULE_NAME_BYTES = 32;
constexpr size_t MAX_SCHEDULE_PROFILE_BYTES = 64;
constexpr size_t MAX_SCHEDULE_TARGET_BYTES = 128;
constexpr size_t MAX_SCHEDULE_PAYLOAD_BYTES = 128;
constexpr uint16_t MIN_HEARTBEAT_INTERVAL_HOURS = 1;
constexpr uint16_t MAX_HEARTBEAT_INTERVAL_HOURS = 240;
constexpr uint16_t DEFAULT_HEARTBEAT_INTERVAL_HOURS = 6;
constexpr uint16_t MIN_KEEPALIVE_TRAFFIC_KB = 1;
constexpr uint16_t MAX_KEEPALIVE_TRAFFIC_KB = 10000;
constexpr uint16_t DEFAULT_KEEPALIVE_TRAFFIC_KB = 1;
constexpr size_t MAX_PUSH_NAME_BYTES = 64;
constexpr size_t MAX_PUSH_URL_BYTES = 512;
constexpr size_t MAX_PUSH_KEY1_BYTES = 256;
constexpr size_t MAX_PUSH_KEY2_BYTES = 256;
constexpr size_t MAX_TITLE_TEMPLATE_BYTES = 256;
constexpr size_t MAX_BODY_TEMPLATE_BYTES = 2048;
constexpr size_t MAX_CUSTOM_BODY_BYTES = 2048;
constexpr size_t MAX_RENDERED_TITLE_BYTES = 256;
constexpr size_t MAX_RENDERED_BODY_BYTES = 8192;
constexpr size_t MAX_RENDERED_CUSTOM_BODY_BYTES = 8192;
constexpr const char NOTIFICATION_LOCALE_ZH_TW[] = "zh-TW";
constexpr const char NOTIFICATION_LOCALE_ZH_CN[] = "zh-CN";
constexpr const char NOTIFICATION_LOCALE_EN[] = "en";
constexpr const char DEFAULT_NOTIFICATION_LOCALE[] = "zh-TW";

#endif
