#ifndef FIRMWARE_VERSION_GENERATED_H
#define FIRMWARE_VERSION_GENERATED_H

#define FIRMWARE_RELEASE_VERSION "1.1.4"
#define FIRMWARE_DEV_BUILD 16
#define FIRMWARE_DEV_BUILD_TEXT "16"
#define FIRMWARE_RELEASE_LABEL "1.1.4 (16)"

#ifndef FIRMWARE_IS_RELEASE
#define FIRMWARE_IS_RELEASE 0
#endif

#if FIRMWARE_IS_RELEASE
#define FIRMWARE_DISPLAY_VERSION FIRMWARE_RELEASE_LABEL
#else
#define FIRMWARE_DISPLAY_VERSION FIRMWARE_DEV_BUILD_TEXT
#endif

#endif
