#!/usr/bin/env python3
"""Generate firmware constants from the current versioned config schema."""

import argparse
import difflib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "dev_doc/config-schema/manifest.json"
FIRMWARE_OUTPUT = ROOT / "code/config_schema_generated.h"
WEB_OUTPUT = ROOT / "web/src/lib/config-schema.generated.ts"


def validate_codec_order(properties: dict) -> None:
    ordered = [field["x-codecOrder"] for field in properties.values()]
    if sorted(ordered) != list(range(len(ordered))):
        raise ValueError("x-codecOrder values must be unique and contiguous")


def validate_string_caps(properties: dict) -> None:
    for name, field in properties.items():
        if field.get("type") == "string" and "x-maxUtf8Bytes" not in field:
            raise ValueError(f"{name} is missing x-maxUtf8Bytes")


def render_firmware(schema: dict, manifest: dict) -> str:
    root = schema["properties"]
    config = root["config"]["properties"]
    channels = config["pushChannels"]
    channel = channels["items"]["properties"]
    accounts = config["webAccounts"]
    account = accounts["items"]["properties"]
    locales = config["notificationLocale"]["enum"]
    push_types = channel["type"]["x-enumMapping"]
    envelope = manifest["backupEnvelope"]
    validate_codec_order(config)
    validate_codec_order(account)
    validate_codec_order(channel)
    validate_string_caps(config)
    validate_string_caps(account)
    validate_string_caps(channel)
    enum_lines = "\n".join(f"  {name} = {value}," for name, value in push_types.items())
    return f"""// Generated by scripts/generate-config-schema.py. Do not edit.
#ifndef CONFIG_SCHEMA_GENERATED_H
#define CONFIG_SCHEMA_GENERATED_H

#include <stddef.h>
#include <stdint.h>

constexpr const char CONFIG_FORMAT[] = \"{root['format']['const']}\";
constexpr const char CONFIG_MIME_TYPE[] = \"{manifest['mimeType']}\";
constexpr uint16_t CONFIG_SCHEMA_VERSION = {root['schemaVersion']['const']};
constexpr size_t MAX_CONFIG_BLOB_SIZE = {manifest['maxBinaryBytes']};
constexpr const char BACKUP_ENVELOPE_MAGIC[] = \"{envelope['magic']}\";
constexpr uint16_t BACKUP_ENVELOPE_VERSION = {envelope['version']};
constexpr uint8_t BACKUP_KDF_ID = {envelope['kdfId']};
constexpr uint32_t BACKUP_KDF_ITERATIONS = {envelope['iterations']};
constexpr size_t BACKUP_SALT_BYTES = {envelope['saltBytes']};
constexpr uint8_t BACKUP_CIPHER_ID = {envelope['cipherId']};
constexpr size_t BACKUP_IV_BYTES = {envelope['ivBytes']};
constexpr size_t BACKUP_TAG_BYTES = {envelope['tagBytes']};
constexpr size_t BACKUP_HEADER_BYTES = {envelope['headerBytes']};
constexpr bool BACKUP_LITTLE_ENDIAN = {'true' if envelope['byteOrder'] == 'little-endian' else 'false'};
constexpr size_t BACKUP_AAD_BYTES = {envelope['aadBytes']};
constexpr size_t MAX_ENCRYPTED_CONFIG_BYTES = {envelope['maxEncryptedBytes']};
#define MAX_PUSH_CHANNELS {channels['x-itemCount']}
#define MAX_WEB_ACCOUNTS {accounts['x-itemCount']}

enum PushType {{
{enum_lines}
}};

constexpr size_t MAX_DEVICE_NAME_BYTES = {config['deviceName']['x-maxUtf8Bytes']};
constexpr size_t MAX_HOSTNAME_LENGTH = {config['hostname']['maxLength']};
constexpr const char PORTABLE_DEVICE_NAME[] = \"{config['deviceName']['x-portableValue']}\";
constexpr const char PORTABLE_HOSTNAME[] = \"{config['hostname']['x-portableValue']}\";
constexpr size_t MAX_NOTIFICATION_LOCALE_BYTES = {config['notificationLocale']['x-maxUtf8Bytes']};
constexpr size_t MAX_SMTP_SERVER_BYTES = {config['smtpServer']['x-maxUtf8Bytes']};
constexpr size_t MAX_SMTP_USER_BYTES = {config['smtpUser']['x-maxUtf8Bytes']};
constexpr size_t MAX_SMTP_PASSWORD_BYTES = {config['smtpPass']['x-maxUtf8Bytes']};
constexpr size_t MAX_SMTP_RECIPIENT_BYTES = {config['smtpSendTo']['x-maxUtf8Bytes']};
constexpr size_t MAX_ADMIN_PHONE_BYTES = {config['adminPhone']['x-maxUtf8Bytes']};
constexpr size_t MAX_BLACKLIST_BYTES = {config['numberBlackList']['x-maxUtf8Bytes']};
constexpr size_t MAX_WEB_USERNAME_BYTES = {account['username']['x-maxUtf8Bytes']};
constexpr size_t MAX_WEB_PASSWORD_BYTES = {account['password']['x-maxUtf8Bytes']};
constexpr size_t MAX_PUSH_NAME_BYTES = {channel['name']['x-maxUtf8Bytes']};
constexpr size_t MAX_PUSH_URL_BYTES = {channel['url']['x-maxUtf8Bytes']};
constexpr size_t MAX_PUSH_KEY1_BYTES = {channel['key1']['x-maxUtf8Bytes']};
constexpr size_t MAX_PUSH_KEY2_BYTES = {channel['key2']['x-maxUtf8Bytes']};
constexpr size_t MAX_TITLE_TEMPLATE_BYTES = {channel['titleTemplate']['x-maxUtf8Bytes']};
constexpr size_t MAX_BODY_TEMPLATE_BYTES = {channel['bodyTemplate']['x-maxUtf8Bytes']};
constexpr size_t MAX_CUSTOM_BODY_BYTES = {channel['customBody']['x-maxUtf8Bytes']};
constexpr size_t MAX_RENDERED_TITLE_BYTES = {channel['titleTemplate']['x-maxRenderedUtf8Bytes']};
constexpr size_t MAX_RENDERED_BODY_BYTES = {channel['bodyTemplate']['x-maxRenderedUtf8Bytes']};
constexpr size_t MAX_RENDERED_CUSTOM_BODY_BYTES = {channel['customBody']['x-maxRenderedUtf8Bytes']};
constexpr const char NOTIFICATION_LOCALE_ZH_TW[] = \"{locales[0]}\";
constexpr const char NOTIFICATION_LOCALE_ZH_CN[] = \"{locales[1]}\";
constexpr const char NOTIFICATION_LOCALE_EN[] = \"{locales[2]}\";
constexpr const char DEFAULT_NOTIFICATION_LOCALE[] = \"{locales[0]}\";

#endif
"""


def render_web(schema: dict, manifest: dict) -> str:
    config = schema["properties"]["config"]["properties"]
    channel = config["pushChannels"]["items"]["properties"]
    account = config["webAccounts"]["items"]["properties"]
    values = {
        "deviceName": config["deviceName"]["x-maxUtf8Bytes"],
        "hostname": config["hostname"]["x-maxUtf8Bytes"],
        "notificationLocale": config["notificationLocale"]["x-maxUtf8Bytes"],
        "smtpServer": config["smtpServer"]["x-maxUtf8Bytes"],
        "smtpUser": config["smtpUser"]["x-maxUtf8Bytes"],
        "smtpPass": config["smtpPass"]["x-maxUtf8Bytes"],
        "smtpSendTo": config["smtpSendTo"]["x-maxUtf8Bytes"],
        "adminPhone": config["adminPhone"]["x-maxUtf8Bytes"],
        "numberBlackList": config["numberBlackList"]["x-maxUtf8Bytes"],
        "webUsername": account["username"]["x-maxUtf8Bytes"],
        "webPassword": account["password"]["x-maxUtf8Bytes"],
        "pushName": channel["name"]["x-maxUtf8Bytes"],
        "pushUrl": channel["url"]["x-maxUtf8Bytes"],
        "pushKey1": channel["key1"]["x-maxUtf8Bytes"],
        "pushKey2": channel["key2"]["x-maxUtf8Bytes"],
        "pushTitleTemplate": channel["titleTemplate"]["x-maxUtf8Bytes"],
        "pushBodyTemplate": channel["bodyTemplate"]["x-maxUtf8Bytes"],
        "pushCustomBody": channel["customBody"]["x-maxUtf8Bytes"],
    }
    limits = json.dumps(values, indent=2, ensure_ascii=False)
    locales = json.dumps(config["notificationLocale"]["enum"], ensure_ascii=False)
    envelope = manifest["backupEnvelope"]
    return f"""// Generated by scripts/generate-config-schema.py. Do not edit.
export const CONFIG_SCHEMA_VERSION = {manifest['currentVersion']} as const;
export const CONFIG_MIME_TYPE = \"{manifest['mimeType']}\" as const;
export const BACKUP_ENVELOPE = {{
  magic: \"{envelope['magic']}\",
  version: {envelope['version']},
  kdfId: {envelope['kdfId']},
  iterations: {envelope['iterations']},
  saltBytes: {envelope['saltBytes']},
  cipherId: {envelope['cipherId']},
  ivBytes: {envelope['ivBytes']},
  tagBytes: {envelope['tagBytes']},
  headerBytes: {envelope['headerBytes']},
  byteOrder: "{envelope['byteOrder']}",
  aad: "{envelope['aad']}",
  aadBytes: {envelope['aadBytes']},
  maxEncryptedBytes: {envelope['maxEncryptedBytes']}
}} as const;
export const CONFIG_FIELD_LIMITS = {limits} as const;
export const NOTIFICATION_LOCALES = {locales} as const;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST_PATH.read_text())
    version = str(manifest["currentVersion"])
    schema_path = MANIFEST_PATH.parent / manifest["versions"][version]
    schema = json.loads(schema_path.read_text())
    if schema["properties"]["format"]["const"] != manifest["format"]:
        raise ValueError("manifest and current schema formats differ")
    envelope = manifest["backupEnvelope"]
    if envelope["byteOrder"] != "little-endian":
        raise ValueError("only the little-endian backup envelope is supported")
    if envelope["aad"] != "header" or envelope["aadBytes"] != envelope["headerBytes"]:
        raise ValueError("backup AAD must cover the complete header")
    if envelope["maxEncryptedBytes"] != manifest["maxBinaryBytes"] + envelope["headerBytes"] + envelope["tagBytes"]:
        raise ValueError("encrypted backup size invariant is invalid")
    expected = {
        FIRMWARE_OUTPUT: render_firmware(schema, manifest),
        WEB_OUTPUT: render_web(schema, manifest),
    }
    if args.check:
        clean = True
        for path, content in expected.items():
            actual = path.read_text() if path.exists() else ""
            if actual != content:
                clean = False
                print("".join(difflib.unified_diff(actual.splitlines(True), content.splitlines(True), fromfile=str(path), tofile="generated")), end="")
        return 0 if clean else 1
    for path, content in expected.items():
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
